/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciopruebafiguras;

/**
 *
 * @author Usuario
 */
public class Ventanafiguras extends javax.swing.JFrame {

    /**
     * Creates new form Ventanafiguras
     */
    public Ventanafiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCperimetro = new javax.swing.JTextField();
        txtCarea = new javax.swing.JTextField();
        txtCradio = new javax.swing.JTextField();
        btnSCperimetro = new javax.swing.JButton();
        btnSCarea = new javax.swing.JButton();
        btnCborrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtlado = new javax.swing.JTextField();
        txtperimetro = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        btnperimetroc = new javax.swing.JButton();
        btnareac = new javax.swing.JButton();
        btnborrarc = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtperimetror = new javax.swing.JTextField();
        txtarear = new javax.swing.JTextField();
        txtalturar = new javax.swing.JTextField();
        txtbaser = new javax.swing.JTextField();
        btnperimetror = new javax.swing.JButton();
        btnarear = new javax.swing.JButton();
        btnborrarR = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtperimetrot = new javax.swing.JTextField();
        txtareat = new javax.swing.JTextField();
        txtalturat = new javax.swing.JTextField();
        txtbaset = new javax.swing.JTextField();
        txttipot = new javax.swing.JTextField();
        btnperimetrot = new javax.swing.JButton();
        btnareat = new javax.swing.JButton();
        btntipot = new javax.swing.JButton();
        btnborrart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("circulo");

        jLabel2.setText("Radio");

        jLabel3.setText("Area");

        jLabel4.setText("Perimetro");

        btnSCperimetro.setText("Calcular perimetro");
        btnSCperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCperimetroActionPerformed(evt);
            }
        });

        btnSCarea.setText("Calcular area");
        btnSCarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCareaActionPerformed(evt);
            }
        });

        btnCborrar.setText("Borrar");
        btnCborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCborrarActionPerformed(evt);
            }
        });

        jLabel5.setText("cuadrado");

        jLabel6.setText("lado");

        jLabel7.setText("area");

        jLabel8.setText("perimetro");

        txtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtareaActionPerformed(evt);
            }
        });

        btnperimetroc.setText("calcular perimetro");
        btnperimetroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperimetrocActionPerformed(evt);
            }
        });

        btnareac.setText("calcular area");
        btnareac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnareacActionPerformed(evt);
            }
        });

        btnborrarc.setText("borrar");
        btnborrarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarcActionPerformed(evt);
            }
        });

        jLabel9.setText("rectangulo");

        jLabel10.setText("base");

        jLabel11.setText("altura");

        jLabel12.setText("area");

        jLabel13.setText("perimetro");

        btnperimetror.setText("calcular perimetro");
        btnperimetror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperimetrorActionPerformed(evt);
            }
        });

        btnarear.setText("calcular area");
        btnarear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarearActionPerformed(evt);
            }
        });

        btnborrarR.setText("borrar");
        btnborrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarRActionPerformed(evt);
            }
        });

        jLabel14.setText("triangulorectangulo");

        jLabel15.setText("base");

        jLabel17.setText("altura");

        jLabel18.setText("tipo");

        jLabel19.setText("area");

        jLabel20.setText("perimetro");

        btnperimetrot.setText("calcular perimetro");
        btnperimetrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperimetrotActionPerformed(evt);
            }
        });

        btnareat.setText("calcular area");
        btnareat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnareatActionPerformed(evt);
            }
        });

        btntipot.setText("tipo");
        btntipot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntipotActionPerformed(evt);
            }
        });

        btnborrart.setText("borrar");
        btnborrart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSCperimetro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSCarea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCborrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCarea, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(txtCradio)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtCperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtbaser))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtperimetror, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtarear, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                        .addComponent(txtalturar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnperimetror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnarear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnborrarR)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtarea)
                                        .addComponent(txtlado))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnperimetroc)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel14)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnareac))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txttipot, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnperimetrot))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnareat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btntipot)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnborrarc)
                                    .addComponent(btnborrart))))
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtperimetrot, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(30, 30, 30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbaset, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtareat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(txtalturat, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(327, 327, 327))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtlado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSCperimetro)
                    .addComponent(btnSCarea)
                    .addComponent(btnCborrar)
                    .addComponent(btnperimetroc)
                    .addComponent(btnareac)
                    .addComponent(btnborrarc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtbaser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtbaset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtalturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtalturat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtarear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtareat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtperimetror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtperimetrot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnperimetror)
                            .addComponent(btnarear)
                            .addComponent(btnborrarR)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txttipot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnperimetrot)
                            .addComponent(btnareat)
                            .addComponent(btntipot)
                            .addComponent(btnborrart))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCborrarActionPerformed
        txtCarea.setText(String.valueOf(""));
        txtCperimetro.setText(String.valueOf(""));
        txtCradio.setText(String.valueOf(""));
    }//GEN-LAST:event_btnCborrarActionPerformed

    private void btnSCperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCperimetroActionPerformed

        int radio = Integer.parseInt(txtCradio.getText());
        Circulo perimetro = new Circulo(radio);
        txtCperimetro.setText(String.valueOf(perimetro.calcularPerimetro()));
    }//GEN-LAST:event_btnSCperimetroActionPerformed

    private void btnSCareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCareaActionPerformed
        int radio = Integer.parseInt(txtCradio.getText());
        Circulo area = new Circulo(radio);
        txtCarea.setText(String.valueOf(area.calcularArea()));
    }//GEN-LAST:event_btnSCareaActionPerformed

    private void btnborrarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarcActionPerformed
        txtarea.setText(String.valueOf(""));
        txtperimetro.setText(String.valueOf(""));
        txtlado.setText(String.valueOf(""));
    }//GEN-LAST:event_btnborrarcActionPerformed

    private void txtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtareaActionPerformed
        
    }//GEN-LAST:event_txtareaActionPerformed

    private void btnperimetrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperimetrocActionPerformed
        int lado = Integer.parseInt(txtlado.getText());
        Cuadrado perimetro = new Cuadrado(lado);
        txtperimetro.setText(String.valueOf(perimetro.calcularPerimetro()));
    }//GEN-LAST:event_btnperimetrocActionPerformed

    private void btnareacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnareacActionPerformed
        int lado = Integer.parseInt(txtlado.getText());
        Cuadrado area = new Cuadrado(lado);
        txtarea.setText(String.valueOf(area.calcularArea()));
    }//GEN-LAST:event_btnareacActionPerformed

    private void btnborrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarRActionPerformed
        txtbaser.setText(String.valueOf(""));
        txtalturar.setText(String.valueOf(""));
        txtarear.setText(String.valueOf(""));
        txtperimetror.setText(String.valueOf(""));
    }//GEN-LAST:event_btnborrarRActionPerformed

    private void btnperimetrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperimetrorActionPerformed
        int base = Integer.parseInt(txtbaser.getText());
        int altura = Integer.parseInt(txtalturar.getText());
        Rectangulo perimetro = new Rectangulo(base,altura);
        txtperimetror.setText(String.valueOf(perimetro.calcularPerimetro()));
    }//GEN-LAST:event_btnperimetrorActionPerformed

    private void btnarearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarearActionPerformed
        int base = Integer.parseInt(txtbaser.getText());
        int altura = Integer.parseInt(txtalturar.getText());
        Rectangulo area = new Rectangulo(base,altura);
        txtarear.setText(String.valueOf(area.calcularArea()));
    }//GEN-LAST:event_btnarearActionPerformed

    private void btnborrartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrartActionPerformed
        txtbaset.setText(String.valueOf(""));
        txtalturat.setText(String.valueOf(""));
        txtareat.setText(String.valueOf(""));
        txtperimetrot.setText(String.valueOf(""));
        txttipot.setText(String.valueOf(""));
    }//GEN-LAST:event_btnborrartActionPerformed

    private void btnperimetrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperimetrotActionPerformed
        int base = Integer.parseInt(txtbaset.getText());
        int altura = Integer.parseInt(txtalturat.getText());
        TrianguloRectangulo perimetro = new TrianguloRectangulo(base,altura);
        txtperimetrot.setText(String.valueOf(perimetro.calcularPerimetro()));
    }//GEN-LAST:event_btnperimetrotActionPerformed

    private void btnareatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnareatActionPerformed
        int base = Integer.parseInt(txtbaset.getText());
        int altura = Integer.parseInt(txtalturat.getText());
        TrianguloRectangulo area = new TrianguloRectangulo(base,altura);
        txtareat.setText(String.valueOf(area.calcularArea()));
    }//GEN-LAST:event_btnareatActionPerformed

    private void btntipotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntipotActionPerformed

        int base = Integer.parseInt(txtbaset.getText());
        int altura = Integer.parseInt(txtalturat.getText());
        TrianguloRectangulo tipo = new TrianguloRectangulo(base,altura);
        txttipot.setText(String.valueOf(tipo.determinarTipoTriangulo()));
    }//GEN-LAST:event_btntipotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanafiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanafiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanafiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanafiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanafiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCborrar;
    private javax.swing.JButton btnSCarea;
    private javax.swing.JButton btnSCperimetro;
    private javax.swing.JButton btnareac;
    private javax.swing.JButton btnarear;
    private javax.swing.JButton btnareat;
    private javax.swing.JButton btnborrarR;
    private javax.swing.JButton btnborrarc;
    private javax.swing.JButton btnborrart;
    private javax.swing.JButton btnperimetroc;
    private javax.swing.JButton btnperimetror;
    private javax.swing.JButton btnperimetrot;
    private javax.swing.JButton btntipot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCarea;
    private javax.swing.JTextField txtCperimetro;
    private javax.swing.JTextField txtCradio;
    private javax.swing.JTextField txtalturar;
    private javax.swing.JTextField txtalturat;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtarear;
    private javax.swing.JTextField txtareat;
    private javax.swing.JTextField txtbaser;
    private javax.swing.JTextField txtbaset;
    private javax.swing.JTextField txtlado;
    private javax.swing.JTextField txtperimetro;
    private javax.swing.JTextField txtperimetror;
    private javax.swing.JTextField txtperimetrot;
    private javax.swing.JTextField txttipot;
    // End of variables declaration//GEN-END:variables
}
