/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciopropuesto19cap3;

/**
 *
 * @author Usuario
 */
public class Ventana19CAP3 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana19CAP3
     */
    public Ventana19CAP3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIlado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSperimetro = new javax.swing.JTextField();
        txtSaltura = new javax.swing.JTextField();
        txtSarea = new javax.swing.JTextField();
        btnCaltura = new javax.swing.JButton();
        btnCperimetro = new javax.swing.JButton();
        btnCarea = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Triangulo equilatero");

        jLabel2.setText("Lado");

        jLabel3.setText("Altura del triangulo");

        jLabel4.setText("Perimetro del triangulo");

        jLabel5.setText("Area del triangulo");

        btnCaltura.setText("Calcular altura");
        btnCaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalturaActionPerformed(evt);
            }
        });

        btnCperimetro.setText("Calcular perimetro");
        btnCperimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCperimetroActionPerformed(evt);
            }
        });

        btnCarea.setText("Calcular area");
        btnCarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCareaActionPerformed(evt);
            }
        });

        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIlado)
                            .addComponent(txtSaltura)
                            .addComponent(txtSperimetro)
                            .addComponent(txtSarea)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCaltura)
                        .addGap(18, 18, 18)
                        .addComponent(btnCperimetro)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarea)
                        .addGap(18, 18, 18)
                        .addComponent(btnborrar)))
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIlado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSperimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaltura)
                    .addComponent(btnCperimetro)
                    .addComponent(btnCarea)
                    .addComponent(btnborrar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalturaActionPerformed
        double altura;
        double lado = Double.parseDouble(txtIlado.getText());
        Triangulo_Equilatero triangulo = new Triangulo_Equilatero(lado);
        altura = triangulo.CalAltura();
        txtSaltura.setText(String.valueOf(altura));
    }//GEN-LAST:event_btnCalturaActionPerformed

    private void btnCperimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCperimetroActionPerformed
        double perimetro;
        double lado = Double.parseDouble(txtIlado.getText());
        Triangulo_Equilatero triangulo = new Triangulo_Equilatero(lado);
        perimetro = triangulo.CalPerimetro();
        txtSperimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnCperimetroActionPerformed

    private void btnCareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCareaActionPerformed
        double area;
        double lado = Double.parseDouble(txtIlado.getText());
        Triangulo_Equilatero triangulo = new Triangulo_Equilatero(lado);
        area = triangulo.CalArea();
        txtSarea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnCareaActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        txtIlado.setText(String.valueOf(""));
        txtSaltura.setText(String.valueOf(""));
        txtSperimetro.setText(String.valueOf(""));
        txtSarea.setText(String.valueOf(""));
    }//GEN-LAST:event_btnborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana19CAP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana19CAP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana19CAP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana19CAP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana19CAP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaltura;
    private javax.swing.JButton btnCarea;
    private javax.swing.JButton btnCperimetro;
    private javax.swing.JButton btnborrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIlado;
    private javax.swing.JTextField txtSaltura;
    private javax.swing.JTextField txtSarea;
    private javax.swing.JTextField txtSperimetro;
    // End of variables declaration//GEN-END:variables
}
